# Generated by Django 5.0.4 on 2024-06-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patbk', '0002_rename_reson_patient_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='reason',
            new_name='reson',
        ),
    ]
