# Generated by Django 5.0.4 on 2024-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patbk', '0003_rename_reason_patient_reson'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pat_time',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
