# Generated by Django 5.0.4 on 2024-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patbk', '0004_patient_pat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pat_time',
            field=models.TimeField(),
        ),
    ]
